%% Figure 3.41 in book
% Color image sharpening


%% Reading img
rgb_img = imread('lenna_RGB.tif');
hsv_img = rgb2hsv(rgb_img);


%% Smoothing
filter = [
     0 -1  0
    -1  4 -1
     0 -1  0
];

rgb_sharpened = rgb_img + cat( ...
    3, ...
    imfilter(rgb_img(:,:,1), filter), ...
    imfilter(rgb_img(:,:,2), filter), ...
    imfilter(rgb_img(:,:,3), filter)  ...
);

hsv_sharpened = rgb_img + uint8(rescale(hsv2rgb( ...
    cat( ...
        3, ...
        hsv_img(:,:,1), ...
        hsv_img(:,:,2), ...
        imfilter(hsv_img(:,:,3), filter) ...
    ) ...
)));


%% Plotting
subplot(2,2,1); imshow(rgb_img);                        title('Original img');
subplot(2,2,2); imshow(rgb_sharpened);                  title('RGB sharpened');
subplot(2,2,3); imshow(hsv_sharpened);                  title('HSV sharpened');
subplot(2,2,4); imshow(rgb_sharpened-hsv_sharpened);    title('Difference of RGB & HSV smoothed');
