%% Example 6.11 in book


%% Reading img
rgb_img = imread('caster_stand.tif');


%% Histogram processing
hsv_img = rgb2hsv(rgb_img);

equalized_img_in_hsv = hsv2rgb( ...
    cat(3, ...
        hsv_img(:,:,1),...
        hsv_img(:,:,2),...
        histeq(hsv_img(:,:,3))...
    ) ...
);

histeq_on_each_rgb_channel = cat(3, ...
    histeq(img(:,:,1)), ...
    histeq(img(:,:,2)), ...
    histeq(img(:,:,3))  ...
);


%% Plotting
subplot(1,3,1); imshow(rgb_img);                    title('Original img');
subplot(1,3,2); imshow(equalized_img_in_hsv);       title('Equalized img');
subplot(1,3,3); imshow(histeq_on_each_rgb_channel); title('Histogram equalization on each RGB channel');
